# Generated by Django 4.2.3 on 2024-11-27 05:18

from django.db import migrations
import fastfood.models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', fastfood.models.CustomUserAdmin()),
            ],
        ),
    ]
