# Generated by Django 4.2.3 on 2024-11-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
